// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobDescriptionGenerator.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("JobFamily", b =>
                {
                    b.Property<int>("JobFamilyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobFamilyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("JobFamilyId");

                    b.ToTable("JobFamilies");

                    b.HasData(
                        new
                        {
                            JobFamilyId = 1,
                            JobFamilyName = "Engineering"
                        },
                        new
                        {
                            JobFamilyId = 2,
                            JobFamilyName = "Operations"
                        });
                });

            modelBuilder.Entity("JobTitle", b =>
                {
                    b.Property<int>("JobTitleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("JobFamilyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobLevelName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JobTitleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("JobTitleId");

                    b.HasIndex("JobFamilyId");

                    b.ToTable("JobTitles");

                    b.HasData(
                        new
                        {
                            JobTitleId = 1,
                            JobFamilyId = 1,
                            JobLevelName = "Job Level - 4",
                            JobTitleName = "Software Engineer"
                        },
                        new
                        {
                            JobTitleId = 2,
                            JobFamilyId = 1,
                            JobLevelName = "Job Level - 6",
                            JobTitleName = "Senior Software Engineer"
                        },
                        new
                        {
                            JobTitleId = 3,
                            JobFamilyId = 2,
                            JobLevelName = "Job Level - 5",
                            JobTitleName = "Operations Analyst"
                        },
                        new
                        {
                            JobTitleId = 4,
                            JobFamilyId = 2,
                            JobLevelName = "Job Level - 8",
                            JobTitleName = "Logistics Manager"
                        });
                });

            modelBuilder.Entity("JobTitle", b =>
                {
                    b.HasOne("JobFamily", "JobFamily")
                        .WithMany("JobTitles")
                        .HasForeignKey("JobFamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobFamily");
                });

            modelBuilder.Entity("JobFamily", b =>
                {
                    b.Navigation("JobTitles");
                });
#pragma warning restore 612, 618
        }
    }
}
